version: '3'
services:
  web:
    build: 
        context: .
        dockerfile: ./php/Dockerfile
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: ../../work/CI_Vue/
        target: /var/www/site/
